#Faça um programa que leia um número de 0 a 9999 e mostre na tela cada um dos dígitos separados.
print ('_____________________________________________________________________')
print ()
print ('## ATIVIDADE PRÁTICA - 23 ##')
print ()
numero = str(input('Digite um número inteiro de 0 a 9999: ').zfill(4))
print ()
print (f'======= {numero} ======= \n')
print (f' - Unidade: {numero[3]}')
print (f' - Dezena: {numero[2]}')
print (f' - Centena: {numero [1]}')
print (f' - Milhar: {numero [0]}')
